// Auto-generated by Miss Elainie Admin App
window.SITE_DATA = [
    {
        "tabName": "Songs",
        "folderName": "songs",
        "files": [
            {
                "name": "Which Way No Cred.m4v",
                "type": "file"
            }
        ]
    },
    {
        "tabName": "Images",
        "folderName": "images",
        "files": [
            {
                "name": "puppies.png",
                "type": "file"
            },
            {
                "name": "puppie 9 27.png",
                "type": "file"
            }
        ]
    },
    {
        "tabName": "Videos",
        "folderName": "videos",
        "files": []
    },
    {
        "tabName": "Documents",
        "folderName": "documents",
        "files": []
    },
    {
        "tabName": "Websites",
        "folderName": "websites",
        "files": [
            {
                "name": "puzzles.txt",
                "type": "link",
                "url": "https://iyampuzzled.org/"
            }
        ]
    }
];